import {
  Destination,
  Place,
  PartnerApplication,
  PartnerOrganization,
  PartnerContentSubmission,
  Article,
  ModeratedReview,
  CustomerLead,
  CustomerUser,
  KnowledgeSource,
  KnowledgeDocument,
  AuditLogEvent,
} from "@/types";

// ─── Initial 8 Vietnam Scenic Destinations ──────────────────
export const INITIAL_DESTINATIONS: Destination[] = [
  {
    id: "ha-long",
    name: "Vịnh Hạ Long",
    slug: "ha-long",
    province: "Quảng Ninh",
    region: "north",
    summary: "Kỳ quan thiên nhiên thế giới UNESCO với hàng ngàn đảo đá vôi kỳ vĩ và làn nước xanh ngọc bích.",
    description: "Vịnh Hạ Long là biểu tượng du lịch hàng đầu Việt Nam, nơi du khách đắm mình giữa khung cảnh non nước ngoạn mục, khám phá các hang động thạch nhũ hàng triệu năm tuổi và trải nghiệm nghỉ dưỡng trên du thuyền sang trọng.",
    history: "Quá trình kiến tạo địa chất Karst kéo dài hơn 500 triệu năm đã tạo nên hàng ngàn hòn đảo hình thù độc đáo.",
    culturalInfo: "Gắn liền với truyền thuyết đàn rồng hạ giới phun châu nhả ngọc bảo vệ bờ cõi nước Nam.",
    center: { lat: 20.9101, lng: 107.0844 },
    startingPrice: 1800000,
    imageUrl: "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1200&q=80",
    heroImageUrl: "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1200&q=80",
    ],
    status: "PUBLISHED",
    isFeatured: true,
    seoTitle: "Du lịch Vịnh Hạ Long trọn gói | Star Travels",
    seoDescription: "Khám phá kỳ quan thế giới UNESCO vịnh Hạ Long với du thuyền 5 sao, chèo kayak và ẩm thực hải sản.",
    updatedAt: "2026-10-04T10:00:00Z",
  },
  {
    id: "hoi-an",
    name: "Phố cổ Hội An",
    slug: "hoi-an",
    province: "Quảng Nam",
    region: "central",
    summary: "Giao thoa giữa nét cổ kính rực rỡ đèn lồng của phố cổ di sản và bờ biển nhiệt đới hiền hòa.",
    description: "Khám phá quần thể phố cổ Hội An với những mái ngói rêu phong, con thuyền hoa đăng trên sông Hoài thơ mộng, cùng bãi biển An Bàng và văn hóa ẩm thực xứ Quảng nức tiếng.",
    history: "Thương cảng quốc tế sầm uất bậc nhất Đông Nam Á từ thế kỷ 16 đến 19 của thương nhân Việt, Hoa, Nhật.",
    culturalInfo: "Lễ hội đêm rằm phố cổ với hàng ngàn hoa đăng lung linh thả trôi dòng sông Hoài.",
    center: { lat: 15.8801, lng: 108.3272 },
    startingPrice: 1200000,
    imageUrl: "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=1200&q=80",
    heroImageUrl: "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=1200&q=80",
    gallery: ["https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=1200&q=80"],
    status: "PUBLISHED",
    isFeatured: true,
    seoTitle: "Phố cổ Hội An — Di sản văn hóa thế giới | Star Travels",
    seoDescription: "Cẩm nang du lịch Hội An: thả hoa đăng, thưởng thức cao lầu và khám phá kiến trúc cổ xưa.",
    updatedAt: "2026-10-04T11:30:00Z",
  },
  {
    id: "phu-quoc",
    name: "Đảo Ngọc Phú Quốc",
    slug: "phu-quoc",
    province: "Kiên Giang",
    region: "south",
    summary: "Thiên đường biển nhiệt đới với bờ cát trắng mịn Bãi Khem, hoàng hôn rực rỡ và làn nước trong vắt.",
    description: "Trải nghiệm lặn biển ngắm san hô, ngắm hoàng hôn Sunset Sanato, ẩm thực hải sản và nghỉ dưỡng cao cấp bên bờ biển.",
    center: { lat: 10.2899, lng: 103.9840 },
    startingPrice: 2200000,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/33/Kem_Beach_aerial_view_Phu_Quoc_Island_Vietnam.jpg",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/33/Kem_Beach_aerial_view_Phu_Quoc_Island_Vietnam.jpg",
    gallery: ["https://upload.wikimedia.org/wikipedia/commons/3/33/Kem_Beach_aerial_view_Phu_Quoc_Island_Vietnam.jpg"],
    status: "PUBLISHED",
    isFeatured: true,
    updatedAt: "2026-10-03T14:20:00Z",
  },
  {
    id: "sa-pa",
    name: "Sa Pa & Fansipan",
    slug: "sa-pa",
    province: "Lào Cai",
    region: "north",
    summary: "Thành phố trong sương với những thửa ruộng bậc thang kỳ vĩ uốn lượn và đỉnh Fansipan 3.143m linh thiêng.",
    description: "Chinh phục nóc nhà Đông Dương Fansipan, ngắm nhìn biển mây bồng bềnh và khám phá văn hóa các dân tộc H'Mông, Dao Đỏ.",
    center: { lat: 22.3364, lng: 103.8438 },
    startingPrice: 1500000,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Terraced_fields_Sa_Pa_Vietnam.JPG",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Terraced_fields_Sa_Pa_Vietnam.JPG",
    gallery: ["https://upload.wikimedia.org/wikipedia/commons/f/fd/Terraced_fields_Sa_Pa_Vietnam.JPG"],
    status: "PUBLISHED",
    isFeatured: true,
    updatedAt: "2026-10-02T09:15:00Z",
  },
  {
    id: "da-lat",
    name: "Đà Lạt — Thành Phố Ngàn Hoa",
    slug: "da-lat",
    province: "Lâm Đồng",
    region: "south",
    summary: "Xứ sở sương mù mộng mơ với đồi thông xanh ngát, hồ Tuyền Lâm phẳng lặng và khí hậu mát lạnh bốn mùa.",
    description: "Đà Lạt là điểm đến lãng mạn bậc nhất Việt Nam với những thung lũng hoa ngập tràn sắc hương và biệt thự Pháp cổ kính.",
    center: { lat: 11.9404, lng: 108.4583 },
    startingPrice: 1400000,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Da_Lat_-_Viet_Nam.jpg",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Da_Lat_-_Viet_Nam.jpg",
    gallery: ["https://upload.wikimedia.org/wikipedia/commons/e/e2/Da_Lat_-_Viet_Nam.jpg"],
    status: "PUBLISHED",
    isFeatured: false,
    updatedAt: "2026-10-01T16:00:00Z",
  },
  {
    id: "ninh-binh",
    name: "Quần thể Tràng An — Tam Cốc",
    slug: "ninh-binh",
    province: "Ninh Bình",
    region: "north",
    summary: "Non nước Tràng An hữu tình, di sản thế giới hỗn hợp đầu tiên của Đông Nam Á.",
    description: "Chèo thuyền vãn cảnh qua các hang động kỳ thú, leo đỉnh Hang Múa ngắm toàn cảnh sông núi Tam Cốc trập trùng.",
    center: { lat: 20.2506, lng: 105.9745 },
    startingPrice: 1100000,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Vietnam%2C_Ninh_Binh%2C_Limestone_peaks.jpg",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Vietnam%2C_Ninh_Binh%2C_Limestone_peaks.jpg",
    gallery: ["https://upload.wikimedia.org/wikipedia/commons/5/5b/Vietnam%2C_Ninh_Binh%2C_Limestone_peaks.jpg"],
    status: "PUBLISHED",
    isFeatured: true,
    updatedAt: "2026-09-30T10:45:00Z",
  },
  {
    id: "hue",
    name: "Cố đô Huế",
    slug: "hue",
    province: "Thừa Thiên Huế",
    region: "central",
    summary: "Kinh thành triều Nguyễn cổ kính, dòng sông Hương thơ mộng, chùa Thiên Mụ và lăng tẩm trầm mặc uy nghiêm.",
    description: "Khám phá nét đẹp cung đình xưa, thưởng thức nhã nhạc cung đình Huế và nét ẩm thực xứ thần kinh thanh nhã.",
    center: { lat: 16.4637, lng: 107.5909 },
    startingPrice: 1300000,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Ngo_Mon.jpg",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Ngo_Mon.jpg",
    gallery: ["https://upload.wikimedia.org/wikipedia/commons/0/0e/Ngo_Mon.jpg"],
    status: "PUBLISHED",
    isFeatured: false,
    updatedAt: "2026-09-28T08:30:00Z",
  },
  {
    id: "ha-giang",
    name: "Hà Giang & Mã Pí Lèng",
    slug: "ha-giang",
    province: "Hà Giang",
    region: "north",
    summary: "Thiên đường hùng vĩ nơi địa đầu Tổ quốc với đèo Mã Pí Lèng hiểm trở và dòng sông Nho Quế xanh như ngọc.",
    description: "Chinh phục những cung đường đèo uốn lượn bên sườn núi đá tai mèo và ngắm mùa hoa tam giác mạch rực rỡ.",
    center: { lat: 22.8233, lng: 104.9839 },
    startingPrice: 1600000,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Mountain_road_at_M%C3%A3_P%C3%AD_L%C3%A8ng_Pass%2C_H%C3%A0_Giang_Province%2C_Vietnam.jpg",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Mountain_road_at_M%C3%A3_P%C3%AD_L%C3%A8ng_Pass%2C_H%C3%A0_Giang_Province%2C_Vietnam.jpg",
    gallery: [],
    status: "DRAFT",
    isFeatured: false,
    updatedAt: "2026-10-04T07:10:00Z",
  },
];

// ─── Initial Places & Local Establishments ──────────────────
export const INITIAL_PLACES: Place[] = [
  {
    id: "place-1",
    name: "Du thuyền 5 sao Paradise Heritage Hạ Long",
    slug: "paradise-heritage-ha-long",
    type: "experience",
    category: "Du thuyền & Nghỉ dưỡng",
    destinationId: "ha-long",
    destinationName: "Vịnh Hạ Long",
    address: "Cảng tàu khách quốc tế Tuần Châu, Hạ Long, Quảng Ninh",
    location: { lat: 20.9250, lng: 107.0125 },
    shortDescription: "Du thuyền gỗ vỏ thép đẳng cấp 5 sao với 28 phòng ban công riêng ngắm vịnh.",
    description: "Hành trình nghỉ dưỡng thượng lưu xuyên qua hang Sửng Sốt, chèo thuyền kayak hang Luồn và tiệc tối hải sản thượng hạng.",
    openingHours: "07:30 - 18:00 (Đón khách hàng ngày)",
    priceRange: "3.500.000 - 6.500.000 ₫",
    contactPhone: "024 3988 7766",
    websiteUrl: "https://paradisevietnam.com",
    imageUrl: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    tags: ["du thuyền", "vịnh hạ long", "5 sao", "kayak"],
    attributes: {
      family_friendly: true,
      romantic: true,
      sea_view: true,
      wifi: true,
      parking: true,
      crowded_level: "medium",
      average_visit_duration: "2 ngày 1 đêm",
    },
    status: "PUBLISHED",
    partnerId: "part-1",
    partnerName: "Paradise Vietnam Hospitality",
    isVerified: true,
    rating: 4.9,
    reviewCount: 142,
    updatedAt: "2026-10-04T12:00:00Z",
  },
  {
    id: "place-2",
    name: "Nhà hàng Bếp Tre Cổ Quán — Phố Cổ Hội An",
    slug: "bep-tre-co-quan-hoi-an",
    type: "restaurant",
    category: "Ẩm thực Di sản",
    destinationId: "hoi-an",
    destinationName: "Phố cổ Hội An",
    address: "88 Trần Phú, Phường Minh An, Hội An, Quảng Nam",
    location: { lat: 15.8775, lng: 108.3285 },
    shortDescription: "Không gian nhà rường gỗ cổ kính phục vụ Cao Lầu, Mì Quảng và Bánh hoa hồng trắng.",
    description: "Bếp Tre Cổ Quán gìn giữ những công thức gia truyền trên 70 năm của nghệ nhân ẩm thực phố Hội.",
    openingHours: "10:00 - 22:00",
    priceRange: "85.000 - 320.000 ₫",
    contactPhone: "0235 386 1234",
    imageUrl: "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    tags: ["ẩm thực", "cao lầu", "phố cổ", "nhà rường"],
    attributes: {
      family_friendly: true,
      quiet: false,
      historical: true,
      indoor: true,
      outdoor: true,
      wifi: true,
      crowded_level: "high",
      average_visit_duration: "1.5 giờ",
    },
    status: "PUBLISHED",
    isVerified: true,
    rating: 4.8,
    reviewCount: 98,
    updatedAt: "2026-10-03T18:10:00Z",
  },
  {
    id: "place-3",
    name: "Quần thể Hang Động Tràng An & Bến Thuyền Nan",
    slug: "quan-the-hang-dong-trang-an",
    type: "attraction",
    category: "Danh thắng Sinh thái",
    destinationId: "ninh-binh",
    destinationName: "Ninh Bình",
    address: "Tràng An, Hoa Lư, Ninh Bình",
    location: { lat: 20.2550, lng: 105.9050 },
    shortDescription: "Tuyến chèo đò nan khám phá 9 hang động xuyên thủy và phim trường Kong Skull Island.",
    description: "Được chèo lái bởi các cô lái đò địa phương thân thiện, hành trình đưa du khách lướt êm qua hang Tối, hang Sáng và đền Trần linh thiêng.",
    openingHours: "07:00 - 17:00",
    priceRange: "250.000 ₫ / vé",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Vietnam%2C_Ninh_Binh%2C_Limestone_peaks.jpg",
    gallery: [],
    tags: ["thuyền nan", "hang động", "tràng an", "unesco"],
    attributes: {
      family_friendly: true,
      quiet: true,
      historical: true,
      outdoor: true,
      wheelchair_accessible: false,
      crowded_level: "high",
      average_visit_duration: "3 giờ",
    },
    status: "PUBLISHED",
    isVerified: true,
    rating: 4.95,
    reviewCount: 310,
    updatedAt: "2026-10-04T08:00:00Z",
  },
  {
    id: "place-4",
    name: "Cafe Gió Rừng & Săn Mây Tà Xùa",
    slug: "cafe-gio-rung-ta-xua",
    type: "cafe",
    category: "Cafe & Điểm Check-in",
    destinationId: "sa-pa",
    destinationName: "Sa Pa & Fansipan",
    address: "Sống lưng khủng long, Háng Đồng, Bắc Yên, Sơn La",
    location: { lat: 21.2800, lng: 104.3500 },
    shortDescription: "Quán cafe gỗ mộc ôm trọn biển mây ngút ngàn và hoàng hôn thung lũng mây.",
    description: "Thưởng thức cà phê pha phin nóng hổi ngắm mây luồn qua đỉnh núi.",
    openingHours: "05:30 - 19:30",
    priceRange: "45.000 - 80.000 ₫",
    imageUrl: "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    tags: ["cafe", "săn mây", "tà xùa", "view đẹp"],
    attributes: {
      romantic: true,
      sea_view: false,
      outdoor: true,
      wifi: true,
      crowded_level: "medium",
      average_visit_duration: "2 giờ",
    },
    status: "PUBLISHED",
    isVerified: true,
    rating: 4.7,
    reviewCount: 84,
    updatedAt: "2026-10-02T15:00:00Z",
  },
];

// ─── Initial Partner Applications ───────────────────────────
export const INITIAL_PARTNER_APPLICATIONS: PartnerApplication[] = [
  {
    id: "app-101",
    businessName: "Du Thuyền Hoàng Gia Lan Hạ Cruises",
    applicantName: "Trần Bảo Long",
    email: "long.tran@lanhacruises.vn",
    phone: "0912 888 777",
    website: "https://lanhacruises.vn",
    businessType: "Du thuyền",
    licenseNumber: "GPKD-0108927491-HP",
    submittedAt: "2026-10-04T09:30:00Z",
    status: "SUBMITTED",
    reviewer: "Chưa phân công",
    riskFlags: ["Hồ sơ mới nộp", "Chưa xác minh chứng chỉ an toàn đường thủy"],
    documents: [
      { name: "Giay_phep_kinh_doanh_2026.pdf", url: "#", verified: true },
      { name: "Chung_chi_dang_kiem_du_thuyen.pdf", url: "#", verified: false },
      { name: "Bao_hiem_trach_nhiem_du_khach.pdf", url: "#", verified: true },
    ],
    requestedListing: "Đăng ký mở bán tour Du Thuyền 3N2Đ và trải nghiệm lặn biển vịnh Lan Hạ.",
    submittedContent: "Cung cấp hải trình mới độc quyền xuyên hang Sáng Tối và bãi tắm Ba Trái Đào.",
    internalNotes: "Cần thẩm định thực địa bến tàu Cát Bà trước ngày 15/10.",
    timeline: [
      { step: "Nộp hồ sơ trực tuyến", actor: "Trần Bảo Long", timestamp: "2026-10-04 09:30", note: "Đã tải lên đủ 3 tài liệu pháp lý" },
      { step: "Tự động kiểm tra trùng lặp", actor: "Hệ thống Star Travels", timestamp: "2026-10-04 09:31", note: "Mã số thuế hợp lệ, không nợ cước phí" },
    ],
  },
  {
    id: "app-102",
    businessName: "Hội An Eco-Craft Village Tours",
    applicantName: "Lê Thị Thảo",
    email: "thao.le@hoianecotours.vn",
    phone: "0905 123 456",
    website: "https://hoianecotours.vn",
    businessType: "Lữ hành bản địa",
    licenseNumber: "GPKD-4001928371-QN",
    submittedAt: "2026-10-03T14:15:00Z",
    status: "UNDER_REVIEW",
    reviewer: "Lê Hải Đăng (PARTNER_REVIEWER)",
    riskFlags: [],
    documents: [
      { name: "Giay_phep_lu_hanh_quoc_te.pdf", url: "#", verified: true },
      { name: "Hop_dong_lang_nghe_gom_Thanh_Ha.pdf", url: "#", verified: true },
    ],
    requestedListing: "Tổ chức tour đạp xe xuyên làng mộc Kim Bồng và làm đèn lồng Hội An.",
    submittedContent: "Gắn kết trực tiếp 40 nghệ nhân bản địa, chia sẻ 30% doanh thu cho cộng đồng.",
    internalNotes: "Hồ sơ rất chuẩn chỉnh, đối tác có uy tín 8 năm tại Quảng Nam.",
    timeline: [
      { step: "Nộp hồ sơ", actor: "Lê Thị Thảo", timestamp: "2026-10-03 14:15" },
      { step: "Tiếp nhận hồ sơ", actor: "Lê Hải Đăng", timestamp: "2026-10-03 16:00", note: "Đã liên hệ xác minh qua số hotline" },
    ],
  },
  {
    id: "app-103",
    businessName: "Sapa Eco-Trek Homestay Cooperative",
    applicantName: "Giàng A Pháo",
    email: "phao.giang@sapaecotrek.org",
    phone: "0984 555 666",
    businessType: "Trải nghiệm dã ngoại",
    licenseNumber: "HTX-5300189201-LC",
    submittedAt: "2026-10-01T08:00:00Z",
    status: "CHANGES_REQUESTED",
    reviewer: "Nguyễn Minh Quân",
    riskFlags: ["Thiếu hợp đồng bảo hiểm leo núi Fansipan bắt buộc"],
    documents: [
      { name: "Dang_ky_hop_tac_xa.pdf", url: "#", verified: true },
    ],
    requestedListing: "Tour trekking Tả Van - Nậm Cang 2N1Đ có người dẫn đường H'Mông.",
    submittedContent: "Hành trình nguyên sơ ngắm ruộng bậc thang và suối nước nóng Nậm Cang.",
    internalNotes: "Đã gửi email yêu cầu bổ sung chứng chỉ sơ cấp cứu đường rừng của 5 porter.",
    timeline: [
      { step: "Nộp hồ sơ", actor: "Giàng A Pháo", timestamp: "2026-10-01 08:00" },
      { step: "Yêu cầu bổ sung chứng chỉ", actor: "Nguyễn Minh Quân", timestamp: "2026-10-02 10:30", note: "Chờ đối tác bổ sung bảo hiểm y tế" },
    ],
  },
];

// ─── Initial Partner Submissions (Current vs Proposed Diff) ─
export const INITIAL_PARTNER_SUBMISSIONS: PartnerContentSubmission[] = [
  {
    id: "sub-201",
    partnerId: "part-1",
    partnerName: "Paradise Vietnam Hospitality",
    entityType: "place",
    entityName: "Du thuyền 5 sao Paradise Heritage Hạ Long",
    submittedAt: "2026-10-04T15:20:00Z",
    status: "PENDING_REVIEW",
    changeSummary: "Nâng cấp lịch trình đón khách, bổ sung tiệc trà chiều hoàng hôn và mở rộng sức chứa.",
    currentData: {
      name: "Du thuyền 5 sao Paradise Heritage Hạ Long",
      openingHours: "07:30 - 18:00 (Đón khách hàng ngày)",
      priceRange: "3.500.000 - 6.500.000 ₫",
      average_visit_duration: "2 ngày 1 đêm",
      highlights: "Hang Sửng Sốt, chèo thuyền kayak hang Luồn.",
    },
    proposedData: {
      name: "Du thuyền 5 sao Paradise Heritage Hạ Long (Bản Mới 2026)",
      openingHours: "07:00 - 18:30 (Đón khách hàng ngày có đưa đón Limousine)",
      priceRange: "3.850.000 - 6.900.000 ₫",
      average_visit_duration: "2 ngày 1 đêm / 3 ngày 2 đêm",
      highlights: "Hang Sửng Sốt, chèo thuyền kayak hang Luồn, tiệc Canapé hoàng hôn trên sundeck & lớp học nấu ăn nem rán cổ truyền.",
    },
  },
  {
    id: "sub-202",
    partnerId: "part-2",
    partnerName: "Bếp Tre Cổ Quán",
    entityType: "opening_hours",
    entityName: "Nhà hàng Bếp Tre Cổ Quán — Phố Cổ Hội An",
    submittedAt: "2026-10-03T11:00:00Z",
    status: "PENDING_REVIEW",
    changeSummary: "Kéo dài giờ mở cửa phục vụ du khách ngắm hoa đăng muộn.",
    currentData: {
      openingHours: "10:00 - 22:00",
      priceRange: "85.000 - 320.000 ₫",
    },
    proposedData: {
      openingHours: "09:30 - 23:30 (Phục vụ ăn đêm phố cổ)",
      priceRange: "90.000 - 350.000 ₫ (Menu mùa hè bổ sung nước thảo mộc Mót)",
    },
  },
];

// ─── Initial Editorial Articles ─────────────────────────────
export const INITIAL_ARTICLES: Article[] = [
  {
    id: "art-1",
    title: "Hành trình xuyên Việt: Chạm vào vẻ đẹp kỳ quan và chiều sâu di sản",
    slug: "hanh-trinh-xuyen-viet",
    excerpt: "Hành trình khám phá văn hóa, ẩm thực và cảnh sắc tuyệt mỹ từ Bắc vào Nam trên dải đất hình chữ S.",
    body: "Việt Nam không chỉ là một điểm đến du lịch, mà là một bản giao hưởng tuyệt sắc của thiên nhiên và lịch sử ngàn năm văn hiến. Bắt đầu từ những dãy núi trùng điệp mù sương của vùng cao Tây Bắc, xuôi về kỳ quan vịnh Hạ Long kỳ vĩ, rồi dừng chân bên những mái ngói rêu phong của phố cổ Hội An, mỗi bước chân đều mở ra một trải nghiệm độc bản.\n\nHãy đi chậm lại, trò chuyện cùng người dân bản địa, thưởng thức một bát phở nóng hổi hay ly cà phê sữa đá vỉa hè. Đó chính là cách bạn cảm nhận trọn vẹn nhịp đập tâm hồn của đất nước này.",
    coverImage: "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1200&q=80",
    destinationSlug: "ha-long",
    destinationName: "Vịnh Hạ Long",
    author: "Ban Biên Tập Di Sản Star Travels",
    status: "PUBLISHED",
    publishAt: "2026-10-01T08:00:00Z",
    tags: ["Xuyên Việt", "Di sản", "Cẩm nang du lịch"],
    updatedAt: "2026-10-01T08:00:00Z",
  },
  {
    id: "art-2",
    title: "Cẩm nang ẩm thực phố cổ: Những hương vị bản địa không thể bỏ lỡ tại Hội An",
    slug: "cam-nang-am-thuc-hoi-an",
    excerpt: "Khám phá thế giới ẩm thực phong phú của Hội An: cao lầu giếng Bá Lễ, mì Quảng, cơm gà và bánh mì giòn rụm.",
    body: "Ẩm thực Hội An là sự kết tinh tinh tế giữa các nền văn hóa Việt - Hoa - Nhật qua nhiều thế kỷ giao thương. Mỗi món ăn nơi đây không chỉ mang hương vị đậm đà khó quên mà còn chứa đựng cả một câu chuyện lịch sử.",
    coverImage: "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=1200&q=80",
    destinationSlug: "hoi-an",
    destinationName: "Phố cổ Hội An",
    author: "Nguyễn Vũ Thụy Trâm",
    status: "PUBLISHED",
    publishAt: "2026-10-02T10:00:00Z",
    tags: ["Ẩm thực", "Hội An", "Đặc sản"],
    updatedAt: "2026-10-02T10:00:00Z",
  },
  {
    id: "art-3",
    title: "Khám phá cung đèo Mã Pí Lèng và hẻm vực Tu Sản sâu nhất Đông Nam Á",
    slug: "kham-pha-ma-pi-leng-ha-giang",
    excerpt: "Kinh nghiệm du lịch bụi Hà Giang mùa hoa tam giác mạch và trải nghiệm thuyền máy trên sông Nho Quế.",
    body: "Nằm trên con đường Hạnh Phúc nối liền thành phố Hà Giang với Đồng Văn và Mèo Vạc, đèo Mã Pí Lèng từ lâu đã trở thành huyền thoại trong lòng những phượt thủ đam mê chinh phục hiểm trở.",
    coverImage: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Mountain_road_at_M%C3%A3_P%C3%AD_L%C3%A8ng_Pass%2C_H%C3%A0_Giang_Province%2C_Vietnam.jpg",
    destinationSlug: "ha-giang",
    destinationName: "Hà Giang & Mã Pí Lèng",
    author: "Đoàn Nam Thắng",
    status: "IN_REVIEW",
    tags: ["Hà Giang", "Mã Pí Lèng", "Trekking"],
    updatedAt: "2026-10-04T16:00:00Z",
  },
];

// ─── Initial Review Moderation Queue ────────────────────────
export const INITIAL_MODERATED_REVIEWS: ModeratedReview[] = [
  {
    id: "rev-301",
    placeName: "Du thuyền 5 sao Paradise Heritage Hạ Long",
    placeSlug: "paradise-heritage-ha-long",
    authorName: "Đỗ Quốc Cường",
    authorEmail: "cuong.do@viettel.com.vn",
    rating: 5,
    body: "Trải nghiệm trên du thuyền tuyệt vời ngoài mong đợi. Đồ ăn hải sản tươi ngon, phòng ngủ hướng trọn biển ngọc vịnh Hạ Long rất thoáng đãng.",
    createdAt: "2026-10-04T11:20:00Z",
    reportCount: 0,
    reportReasons: [],
    status: "PUBLISHED",
    moderationHistory: [],
  },
  {
    id: "rev-302",
    placeName: "Nhà hàng Bếp Tre Cổ Quán — Phố Cổ Hội An",
    placeSlug: "bep-tre-co-quan-hoi-an",
    authorName: "Anonymous User 92",
    authorEmail: "spam_bot99@tempmail.org",
    rating: 1,
    body: "Quán ăn lừa đảo, mọi người đừng vào, hãy qua quán số 45 cạnh bên ngon và rẻ hơn gấp mười lần!",
    createdAt: "2026-10-04T08:15:00Z",
    reportCount: 4,
    reportReasons: ["Spam / Quảng cáo đối thủ cạnh tranh không lành mạnh", "Ngôn từ thù ghét"],
    status: "REPORTED",
    moderationHistory: [
      { action: "Hệ thống tự động gắn cờ", moderator: "Auto-Mod Algorithm", timestamp: "2026-10-04 08:20", reason: "Từ khóa quảng cáo đối thủ" },
    ],
  },
  {
    id: "rev-303",
    placeName: "Quần thể Hang Động Tràng An & Bến Thuyền Nan",
    placeSlug: "quan-the-hang-dong-trang-an",
    authorName: "Emma Watson",
    authorEmail: "emma.w@britishcouncil.org",
    rating: 5,
    body: "Breathtaking natural beauty! The rowing lady was so sweet and sang traditional Vietnamese folk songs while passing through the limestone caves.",
    createdAt: "2026-10-03T16:40:00Z",
    reportCount: 0,
    reportReasons: [],
    status: "PUBLISHED",
    moderationHistory: [],
  },
];

// ─── Initial CRM-Lite Leads ─────────────────────────────────
export const INITIAL_LEADS: CustomerLead[] = [
  {
    id: "lead-401",
    name: "Hoàng Anh Tuấn",
    email: "tuan.hoang@vinfast.vn",
    phone: "0912 345 678",
    source: "website",
    destinationInterest: "Vịnh Hạ Long",
    estimatedBudget: "80.000.000 ₫",
    status: "NEW",
    assignedStaff: "Lê Thị Cẩm Nhung (Tư vấn VIP)",
    message: "Cần đặt trọn gói 6 cabin VIP trên du thuyền Hạ Long cho ban lãnh đạo công ty ngày 18/11/2026.",
    createdAt: "2026-10-04T10:15:00Z",
    updatedAt: "2026-10-04T10:15:00Z",
    internalNotes: [
      { id: "n-1", author: "Lê Thị Cẩm Nhung", text: "Khách VIP tập đoàn lớn, cần gửi proposal thực đơn gala dinner cao cấp trong chiều nay.", createdAt: "2026-10-04 10:30" }
    ],
    timeline: [
      { title: "Khách gửi biểu mẫu liên hệ trên Website", timestamp: "2026-10-04 10:15", actor: "Khách hàng" },
      { title: "Tự động phân công chuyên viên VIP", timestamp: "2026-10-04 10:16", actor: "CRM Automation" },
    ],
  },
  {
    id: "lead-402",
    name: "David Wilson",
    email: "david.w@cathaypacific.com",
    phone: "+852 9123 4567",
    source: "ai_assistant",
    destinationInterest: "Sa Pa & Fansipan",
    estimatedBudget: "$1,500 USD",
    status: "ASSIGNED",
    assignedStaff: "Trần Văn Bình (English Guide)",
    message: "Seeking a private hiking guide for 4 people up Mount Fansipan via Trạm Tôn trail.",
    createdAt: "2026-10-03T15:20:00Z",
    updatedAt: "2026-10-04T09:00:00Z",
    internalNotes: [
      { id: "n-2", author: "Trần Văn Bình", text: "Đã gửi qua email file PDF hướng dẫn chuẩn bị thể lực và trang phục leo núi.", createdAt: "2026-10-04 09:00" }
    ],
    timeline: [
      { title: "Khởi tạo từ phiên hỏi đáp AI Trợ lý du lịch", timestamp: "2026-10-03 15:20", actor: "Star Travels AI" },
      { title: "Chuyển giao cho bộ phận điều hành tour Tây Bắc", timestamp: "2026-10-03 16:00", actor: "Hệ thống" },
    ],
  },
  {
    id: "lead-403",
    name: "Trần Thị Mai Phương",
    email: "phuong.tran@vietcombank.com.vn",
    phone: "0903 888 222",
    source: "zalo",
    destinationInterest: "Phú Quốc",
    estimatedBudget: "45.000.000 ₫",
    status: "QUALIFIED",
    assignedStaff: "Nguyễn Hải Yến",
    message: "Đặt tour nghỉ dưỡng gia đình 3 thế hệ tại Bãi Khem Phú Quốc, cần phòng thông nhau và xe đưa đón người cao tuổi.",
    createdAt: "2026-10-02T11:00:00Z",
    updatedAt: "2026-10-03T14:00:00Z",
    internalNotes: [
      { id: "n-3", author: "Nguyễn Hải Yến", text: "Khách đã chốt ngày 24-27/10, đang đợi khách chọn giữa Marriott và Premier Village.", createdAt: "2026-10-03 14:00" }
    ],
    timeline: [
      { title: "Khách nhắn tin qua Zalo OA", timestamp: "2026-10-02 11:00", actor: "Khách hàng" },
      { title: "Tư vấn viên gọi điện tư vấn chi tiết", timestamp: "2026-10-02 14:00", actor: "Nguyễn Hải Yến" },
      { title: "Xác nhận hồ sơ Đạt tiêu chuẩn (Qualified)", timestamp: "2026-10-03 14:00", actor: "Nguyễn Hải Yến" },
    ],
  },
];

// ─── Initial AI Knowledge Base ──────────────────────────────
export const INITIAL_KNOWLEDGE_SOURCES: KnowledgeSource[] = [
  {
    id: "src-1",
    name: "Cổng thông tin Cục Du lịch Quốc gia Việt Nam (VNAT)",
    type: "editorial_corpus",
    sourceUrl: "https://vietnamtourism.gov.vn",
    trustLevel: "HIGH",
    status: "ACTIVE",
    lastCrawledAt: "2026-10-04 03:00",
    documentCount: 84,
  },
  {
    id: "src-2",
    name: "Hồ sơ Di sản Thế giới UNESCO Tràng An & Hạ Long",
    type: "document",
    sourceUrl: "https://whc.unesco.org/en/list/1438",
    trustLevel: "HIGH",
    status: "ACTIVE",
    lastCrawledAt: "2026-09-25 10:00",
    documentCount: 32,
  },
  {
    id: "src-3",
    name: "Kênh dữ liệu giá & dịch vụ đối tác thẩm định",
    type: "partner_feed",
    sourceUrl: "internal://star-travels/partner-feed",
    trustLevel: "HIGH",
    status: "ACTIVE",
    lastCrawledAt: "2026-10-04 12:00",
    documentCount: 128,
  },
];

export const INITIAL_KNOWLEDGE_DOCUMENTS: KnowledgeDocument[] = [
  {
    id: "doc-501",
    title: "Lịch sử kiến tạo Karst và hang động ngầm Vịnh Hạ Long",
    sourceId: "src-2",
    sourceName: "UNESCO World Heritage Centre",
    destination: "Vịnh Hạ Long",
    contentType: "historical",
    language: "vi",
    isVerified: true,
    lastUpdated: "2026-10-03",
    indexStatus: "INDEXED",
    chunkCount: 16,
    contentSnippet: "Quá trình Karst hóa diễn ra qua 2 giai đoạn chính trong kỷ Đệ Tứ, tạo ra hệ thống chìm ngập karst hoàn chỉnh nhất thế giới...",
  },
  {
    id: "doc-502",
    title: "Quy chuẩn an toàn lặn biển ngắm san hô tại Nam Phú Quốc",
    sourceId: "src-3",
    sourceName: "Đối tác lữ hành Star Travels",
    destination: "Phú Quốc",
    contentType: "scenic",
    language: "vi",
    isVerified: true,
    lastUpdated: "2026-10-04",
    indexStatus: "INDEXED",
    chunkCount: 8,
    contentSnippet: "Tất cả du khách bắt buộc phải mặc áo phao cứu sinh chuyên dụng, đi kèm hướng dẫn viên bản địa đạt chứng chỉ PADI...",
  },
  {
    id: "doc-503",
    title: "Cẩm nang văn hóa ẩm thực và nghi thức thả đèn hoa đăng sông Hoài",
    sourceId: "src-1",
    sourceName: "Cục Du lịch Quốc gia Việt Nam",
    destination: "Hội An",
    contentType: "culture",
    language: "vi",
    isVerified: true,
    lastUpdated: "2026-10-01",
    indexStatus: "INDEXED",
    chunkCount: 12,
    contentSnippet: "Nghi thức thả đèn hoa đăng bắt nguồn từ thế kỷ 17 với ý niệm cầu bình an, may mắn cho gia đình và tỏ lòng tri ân nguồn cội...",
  },
  {
    id: "doc-504",
    title: "Dữ liệu địa hình và thời tiết bốn mùa đèo Mã Pí Lèng Hà Giang",
    sourceId: "src-1",
    sourceName: "Cục Du lịch Quốc gia Việt Nam",
    destination: "Hà Giang",
    contentType: "logistics",
    language: "vi",
    isVerified: false,
    lastUpdated: "2026-10-04",
    indexStatus: "PENDING",
    chunkCount: 10,
    contentSnippet: "Đèo có độ dài 20km nằm ở độ cao 1.200m, thường xuất hiện sương mù dày đặc vào các tháng mùa đông từ tháng 11 đến tháng 2...",
  },
];

// ─── Initial Immutable Audit Log Events ─────────────────────
export const INITIAL_AUDIT_EVENTS: AuditLogEvent[] = [
  {
    id: "aud-001",
    actor: "Nguyễn Minh Quân",
    actorRole: "SUPER_ADMIN",
    action: "APPROVE_PARTNER_APPLICATION",
    entityType: "partner",
    entityId: "app-098",
    entityName: "Hạ Long Paradise Cruises",
    timestamp: "2026-10-04 14:32:10",
    ipAddress: "113.161.42.18",
    metadata: { applicationStatus: "APPROVED", commission: "12%", reviewerNote: "Hồ sơ an toàn đạt chuẩn 100%" },
  },
  {
    id: "aud-002",
    actor: "Trần Mai Anh",
    actorRole: "CONTENT_EDITOR",
    action: "PUBLISH_DESTINATION",
    entityType: "destination",
    entityId: "ha-long",
    entityName: "Vịnh Hạ Long",
    timestamp: "2026-10-04 11:20:45",
    ipAddress: "14.162.188.75",
    metadata: { previousStatus: "IN_REVIEW", newStatus: "PUBLISHED", isFeatured: true },
  },
  {
    id: "aud-003",
    actor: "Lê Hải Đăng",
    actorRole: "MODERATOR",
    action: "HIDE_SPAM_REVIEW",
    entityType: "review",
    entityId: "rev-299",
    entityName: "Đánh giá Bếp Tre Cổ Quán",
    timestamp: "2026-10-04 09:14:02",
    ipAddress: "115.79.138.204",
    metadata: { reason: "Cạnh tranh không lành mạnh / Spam link", reportedByCount: 4 },
  },
  {
    id: "aud-004",
    actor: "Lê Thị Cẩm Nhung",
    actorRole: "OPERATIONS_MANAGER",
    action: "ASSIGN_CRM_LEAD",
    entityType: "lead",
    entityId: "lead-401",
    entityName: "Hoàng Anh Tuấn (VinFast Group)",
    timestamp: "2026-10-04 10:16:00",
    ipAddress: "118.69.182.11",
    metadata: { assignedTo: "Lê Thị Cẩm Nhung", priority: "HIGH", estimatedValue: "80.000.000 ₫" },
  },
  {
    id: "aud-005",
    actor: "Nguyễn Minh Quân",
    actorRole: "SUPER_ADMIN",
    action: "TRIGGER_KNOWLEDGE_REINDEX",
    entityType: "knowledge",
    entityId: "doc-501",
    entityName: "Lịch sử kiến tạo Karst Hạ Long",
    timestamp: "2026-10-03 16:45:19",
    ipAddress: "113.161.42.18",
    metadata: { chunksGenerated: 16, embeddingModel: "text-embedding-004", status: "SUCCESS" },
  },
];
