import type { Destination } from "./types";
import { VIETNAM_IMAGES } from "./assets";

export const VIETNAM_DESTINATIONS_PAGES: Destination[][] = [
  // TRANG 1: 4 Điểm đến miền Bắc, Trung, Nam tiêu biểu
  [
    {
      id: "ha-long",
      slug: "ha-long",
      name: "Vịnh Hạ Long",
      country: "Quảng Ninh, Việt Nam",
      summary: "Kỳ quan thiên nhiên thế giới UNESCO với hàng ngàn đảo đá vôi kỳ vĩ và làn nước xanh ngọc bích.",
      description: "Vịnh Hạ Long là niềm tự hào của du lịch Việt Nam, nơi du khách đắm mình giữa khung cảnh non nước ngoạn mục.",
      image_url: VIETNAM_IMAGES.haLong,
      hero_image_url: VIETNAM_IMAGES.haLong,
      starting_price: "1800000",
      center: { lat: 20.9101, lng: 107.0844 },
    },
    {
      id: "hoi-an",
      slug: "hoi-an",
      name: "Phố cổ Hội An",
      country: "Quảng Nam, Việt Nam",
      summary: "Phố cổ di sản rực rỡ sắc màu đèn lồng, những mái ngói rêu phong và con thuyền hoa đăng trên sông Hoài thơ mộng.",
      description: "Khám phá nét văn hóa giao thương thế kỷ 17 với kiến trúc cổ kính và ẩm thực phong phú.",
      image_url: VIETNAM_IMAGES.hoiAn,
      hero_image_url: VIETNAM_IMAGES.hoiAn,
      starting_price: "1200000",
      center: { lat: 15.8801, lng: 108.3272 },
    },
    {
      id: "phu-quoc",
      slug: "phu-quoc",
      name: "Đảo Ngọc Phú Quốc",
      country: "Kiên Giang, Việt Nam",
      summary: "Thiên đường biển nhiệt đới với bờ cát trắng mịn Bãi Khem, hoàng hôn rực rỡ và làn nước trong vắt.",
      description: "Trải nghiệm lặn biển ngắm san hô, ẩm thực hải sản và nghỉ dưỡng cao cấp bên bờ biển.",
      image_url: VIETNAM_IMAGES.phuQuoc,
      hero_image_url: VIETNAM_IMAGES.phuQuoc,
      starting_price: "2200000",
      center: { lat: 10.2899, lng: 103.984 },
    },
    {
      id: "sa-pa",
      slug: "sa-pa",
      name: "Sa Pa & Fansipan",
      country: "Lào Cai, Việt Nam",
      summary: "Thành phố trong sương với những thửa ruộng bậc thang kỳ vĩ uốn lượn và đỉnh Fansipan 3.143m linh thiêng.",
      description: "Chinh phục nóc nhà Đông Dương, săn mây ngút ngàn và tìm hiểu bản sắc văn hóa các dân tộc vùng cao.",
      image_url: VIETNAM_IMAGES.saPa,
      hero_image_url: VIETNAM_IMAGES.saPa,
      starting_price: "1500000",
      center: { lat: 22.3364, lng: 103.8438 },
    },
  ],

  // TRANG 2: Đà Lạt, Tràng An Ninh Bình, Cố đô Huế, Hà Giang
  [
    {
      id: "da-lat",
      slug: "da-lat",
      name: "Đà Lạt — Ngàn Hoa",
      country: "Lâm Đồng, Việt Nam",
      summary: "Xứ sở sương mù mộng mơ với đồi thông xanh ngát, hồ Tuyền Lâm phẳng lặng và khí hậu mát lạnh bốn mùa.",
      description: "Đà Lạt là điểm đến lãng mạn bậc nhất Việt Nam với những thung lũng hoa ngập tràn sắc hương và biệt thự kiểu Pháp cổ.",
      image_url: VIETNAM_IMAGES.daLat,
      hero_image_url: VIETNAM_IMAGES.daLat,
      starting_price: "1400000",
      center: { lat: 11.9404, lng: 108.4583 },
    },
    {
      id: "ninh-binh",
      slug: "ninh-binh",
      name: "Quần thể Tràng An",
      country: "Ninh Bình, Việt Nam",
      summary: "Di sản thế giới kép UNESCO với non nước hữu tình, Tam Cốc Bích Động và thung lũng đá vôi huyền ảo.",
      description: "Trải nghiệm ngồi thuyền nan lướt nhẹ qua những hang động kỳ bí và chiêm bái các ngôi chùa cổ ngàn năm.",
      image_url: VIETNAM_IMAGES.ninhBinh,
      hero_image_url: VIETNAM_IMAGES.ninhBinh,
      starting_price: "1100000",
      center: { lat: 20.2506, lng: 105.9745 },
    },
    {
      id: "hue",
      slug: "hue",
      name: "Cố đô Huế",
      country: "Thừa Thiên Huế, Việt Nam",
      summary: "Kinh thành triều Nguyễn cổ kính, dòng sông Hương thơ mộng, chùa Thiên Mụ và lăng tẩm trầm mặc uy nghiêm.",
      description: "Khám phá nét đẹp cung đình xưa, thưởng thức nhã nhạc cung đình Huế và nét ẩm thực xứ thần kinh thanh nhã.",
      image_url: VIETNAM_IMAGES.hue,
      hero_image_url: VIETNAM_IMAGES.hue,
      starting_price: "1300000",
      center: { lat: 16.4637, lng: 107.5909 },
    },
    {
      id: "ha-giang",
      slug: "ha-giang",
      name: "Hà Giang & Mã Pí Lèng",
      country: "Hà Giang, Việt Nam",
      summary: "Thiên đường hùng vĩ nơi địa đầu Tổ quốc với đèo Mã Pí Lèng hiểm trở và dòng sông Nho Quế xanh như ngọc.",
      description: "Chinh phục những cung đường đèo uốn lượn bên sườn núi đá tai mèo và ngắm mùa hoa tam giác mạch rực rỡ.",
      image_url: VIETNAM_IMAGES.haGiang,
      hero_image_url: VIETNAM_IMAGES.haGiang,
      starting_price: "1600000",
      center: { lat: 22.8233, lng: 104.9839 },
    },
  ],

  // TRANG 3: Đà Nẵng, Côn Đảo, Phong Nha, Mũi Né
  [
    {
      id: "da-nang",
      slug: "da-nang",
      name: "Đà Nẵng — Đáng Sống",
      country: "Đà Nẵng, Việt Nam",
      summary: "Thành phố biển hiện đại với bãi biển Mỹ Khê quyến rũ, bán đảo Sơn Trà và những cây cầu biểu tượng rực rỡ.",
      description: "Đà Nẵng kết hợp hoàn hảo giữa du lịch nghỉ dưỡng biển cao cấp và khám phá thiên nhiên sinh thái đa dạng.",
      image_url: VIETNAM_IMAGES.daNang,
      hero_image_url: VIETNAM_IMAGES.daNang,
      starting_price: "1350000",
      center: { lat: 16.0544, lng: 108.2022 },
    },
    {
      id: "con-dao",
      slug: "con-dao",
      name: "Côn Đảo Huyền Thoại",
      country: "Bà Rịa - Vũng Tàu, Việt Nam",
      summary: "Vẻ đẹp nguyên sơ của biển xanh màu ngọc bích, bãi Đầm Trầu hoang sơ và chiều sâu lịch sử hào hùng.",
      description: "Một trong những hòn đảo quyến rũ và bí ẩn nhất châu Á với rùa biển đẻ trứng và rạn san hô cổ thụ.",
      image_url: VIETNAM_IMAGES.conDao,
      hero_image_url: VIETNAM_IMAGES.conDao,
      starting_price: "2500000",
      center: { lat: 8.6835, lng: 106.6083 },
    },
    {
      id: "phong-nha",
      slug: "phong-nha",
      name: "Phong Nha — Kẻ Bàng",
      country: "Quảng Bình, Việt Nam",
      summary: "Vương quốc hang động thế giới với Sơn Đoòng kỳ vĩ, động Thiên Đường tráng lệ và sông Son êm đềm.",
      description: "Hành trình thám hiểm hang động hàng đầu hành tinh, đắm mình giữa rừng nguyên sinh nhiệt đới cổ xưa.",
      image_url: VIETNAM_IMAGES.ninhBinh,
      hero_image_url: VIETNAM_IMAGES.ninhBinh,
      starting_price: "1750000",
      center: { lat: 17.5898, lng: 106.2829 },
    },
    {
      id: "mui-ne",
      slug: "mui-ne",
      name: "Mũi Né — Đồi Cát Bay",
      country: "Bình Thuận, Việt Nam",
      summary: "Tiểu sa mạc cát đỏ cát trắng thơ mộng, rặng dừa xanh nghiêng bóng và thiên đường lướt ván diều.",
      description: "Thưởng ngoạn vẻ đẹp độc đáo của đồi cát lúc bình minh, ngắm nhìn làng chài tấp nập thuyền thúng vào bờ.",
      image_url: VIETNAM_IMAGES.oceanBanner,
      hero_image_url: VIETNAM_IMAGES.oceanBanner,
      starting_price: "1250000",
      center: { lat: 10.9333, lng: 108.2833 },
    },
  ],
];

export const ALL_VIETNAM_DESTINATIONS: Destination[] = VIETNAM_DESTINATIONS_PAGES.flat();
