import type { Place } from "./types";
import { VIETNAM_IMAGES } from "./assets";

export const VIETNAM_EXPERIENCES: Place[] = [
  {
    id: "ha-long-cruise",
    slug: "ha-long-cruise",
    name: "Du Thuyền 5 Sao Vịnh Hạ Long",
    short_description: "Nghỉ dưỡng thượng lưu và ngắm trọn vẹn cảnh sắc hoàng hôn kỳ vĩ trên vịnh di sản UNESCO.",
    description: "Hành trình 2 ngày 1 đêm trên du thuyền sang trọng chuẩn quốc tế, đưa quý khách len lỏi qua hàng ngàn đảo đá vôi kỳ vĩ của vịnh Hạ Long và vịnh Lan Hạ. Thưởng thức đại tiệc hải sản tươi ngon, chèo kayak khám phá hang Sửng Sốt, câu mực đêm cùng ngư dân và đón bình minh với bài tập Thái Cực Quyền trên boong tàu.",
    image_url: VIETNAM_IMAGES.cruise,
    address: "Cảng tàu khách quốc tế Hạ Long, Bãi Cháy, Quảng Ninh",
    location: { lat: 20.9101, lng: 107.0844 },
    destination: {
      id: "ha-long",
      slug: "ha-long",
      name: "Vịnh Hạ Long",
      country: "Quảng Ninh, Việt Nam",
      summary: "Kỳ quan thiên nhiên thế giới UNESCO.",
      description: "Vịnh Hạ Long là niềm tự hào của du lịch Việt Nam.",
      image_url: VIETNAM_IMAGES.haLong,
      hero_image_url: VIETNAM_IMAGES.haLong,
      starting_price: "1800000",
      center: { lat: 20.9101, lng: 107.0844 },
    },
    category: {
      id: "du-thuyen",
      slug: "du-thuyen",
      name: "Du Thuyền & Nghỉ Dưỡng",
    },
    average_rating: "5.0",
    review_count: 248,
  },
  {
    id: "kayak-lan-ha",
    slug: "kayak-lan-ha",
    name: "Chèo Kayak Hang Sáng Tối - Vịnh Lan Hạ",
    short_description: "Lướt nhẹ mái chèo xuyên qua vòm hang nước ngầm kỳ ảo và làn nước ngọc bích nguyên sơ.",
    description: "Trải nghiệm tự tay điều khiển thuyền kayak xuyên qua hang Sáng - hang Tối huyền ảo, dẫn lối vào những thung lũng nước phẳng lặng như gương được bao bọc bởi những vách đá vôi sừng sững phủ kín cây xanh nguyên sinh.",
    image_url: VIETNAM_IMAGES.kayak,
    address: "Khu bảo tồn Vịnh Lan Hạ, Quần đảo Cát Bà, Hải Phòng",
    location: { lat: 20.85, lng: 107.05 },
    destination: {
      id: "ha-long",
      slug: "ha-long",
      name: "Vịnh Lan Hạ - Cát Bà",
      country: "Hải Phòng, Việt Nam",
      summary: "Vịnh biển nguyên sơ với hàng trăm bãi cát tự nhiên.",
      description: "Nơi lý tưởng cho các hoạt động thể thao nước ngoài trời.",
      image_url: VIETNAM_IMAGES.kayak,
      hero_image_url: VIETNAM_IMAGES.kayak,
      starting_price: "850000",
      center: { lat: 20.85, lng: 107.05 },
    },
    category: {
      id: "kayak-the-thao-nuoc",
      slug: "kayak-the-thao-nuoc",
      name: "Chèo Kayak & Thể Thao Nước",
    },
    average_rating: "4.9",
    review_count: 182,
  },
  {
    id: "trekking-fansipan",
    slug: "trekking-fansipan",
    name: "Trekking Chinh Phục Nóc Nhà Đông Dương Fansipan",
    short_description: "Hành trình thử thách sức bền vượt rừng trúc nguyên sinh chạm mốc đỉnh cao 3.143m.",
    description: "Chinh phục đỉnh núi cao nhất bán đảo Đông Dương theo cung đường Trạm Tôn. Quý khách sẽ băng qua những cánh rừng đỗ quyên rực rỡ, rừng trúc xanh ngắt, vượt qua những con dốc đá hiểm trở để chạm tay vào chóp kim loại 3.143m linh thiêng giữa biển mây Tây Bắc.",
    image_url: VIETNAM_IMAGES.hiking,
    address: "Vườn quốc gia Hoàng Liên, Thị xã Sa Pa, Lào Cai",
    location: { lat: 22.3033, lng: 103.775 },
    destination: {
      id: "sa-pa",
      slug: "sa-pa",
      name: "Sa Pa & Fansipan",
      country: "Lào Cai, Việt Nam",
      summary: "Thành phố trong sương và đỉnh Fansipan linh thiêng.",
      description: "Điểm đến trekking và nghỉ dưỡng hàng đầu miền Bắc.",
      image_url: VIETNAM_IMAGES.saPa,
      hero_image_url: VIETNAM_IMAGES.saPa,
      starting_price: "1650000",
      center: { lat: 22.3364, lng: 103.8438 },
    },
    category: {
      id: "trekking-leo-nui",
      slug: "trekking-leo-nui",
      name: "Trekking & Leo Núi",
    },
    average_rating: "4.9",
    review_count: 156,
  },
  {
    id: "camping-ta-xua",
    slug: "camping-ta-xua",
    name: "Cắm Trại Đón Bình Minh Biển Mây Tà Xùa",
    short_description: "Thức giấc giữa biển mây trắng ngút ngàn, quây quần bên đống lửa ấm và ngắm bình minh.",
    description: "Trải nghiệm cắm trại đêm trên sống lưng khủng long Tà Xùa. Tận hưởng không khí se lạnh vùng cao, quây quần bên bếp lửa hồng cùng tiệc nướng BBQ thịt bản, và đón nhận khoảnh khắc vỡ òa khi ánh bình minh dát vàng lên đại dương mây bồng bềnh trải dài đến tận chân trời.",
    image_url: VIETNAM_IMAGES.camping,
    address: "Đỉnh Gió, Xã Tà Xùa, Huyện Bắc Yên, Sơn La",
    location: { lat: 21.28, lng: 104.35 },
    destination: {
      id: "ta-xua",
      slug: "ta-xua",
      name: "Tà Xùa — Thiên Đường Mây",
      country: "Sơn La, Việt Nam",
      summary: "Thiên đường săn mây kỳ vĩ bậc nhất vùng Tây Bắc.",
      description: "Điểm cắm trại và dã ngoại được yêu thích bởi giới trẻ.",
      image_url: VIETNAM_IMAGES.camping,
      hero_image_url: VIETNAM_IMAGES.camping,
      starting_price: "1200000",
      center: { lat: 21.28, lng: 104.35 },
    },
    category: {
      id: "cam-trai-da-ngoai",
      slug: "cam-trai-da-ngoai",
      name: "Cắm Trại & Dã Ngoại",
    },
    average_rating: "4.8",
    review_count: 194,
  },
  {
    id: "scuba-diving-phu-quoc",
    slug: "scuba-diving-phu-quoc",
    name: "Lặn Biển Ngắm San Hô Hòn Thơm Phú Quốc",
    short_description: "Khám phá lòng đại dương và hệ sinh thái san hô rực rỡ nhất Nam đảo Ngọc Phú Quốc.",
    description: "Được trang bị bình khí và thiết bị lặn chuyên dụng chuẩn PADI cùng sự kèm cặp 1-1 của thợ lặn giàu kinh nghiệm. Bạn sẽ được chiêm ngưỡng thế giới thủy cung đầy mê hoặc với những rạn san hô bắp cải, san hô sừng hươu quý hiếm và đàn cá nhiệt đới đủ màu sắc lượn quanh.",
    image_url: VIETNAM_IMAGES.scubaDiving,
    address: "Quần đảo An Thới, Nam Phú Quốc, Kiên Giang",
    location: { lat: 10.015, lng: 104.015 },
    destination: {
      id: "phu-quoc",
      slug: "phu-quoc",
      name: "Đảo Ngọc Phú Quốc",
      country: "Kiên Giang, Việt Nam",
      summary: "Thiên đường biển đảo nhiệt đới với bờ cát trắng mịn.",
      description: "Thủ phủ lặn biển và nghỉ dưỡng biển cao cấp.",
      image_url: VIETNAM_IMAGES.phuQuoc,
      hero_image_url: VIETNAM_IMAGES.phuQuoc,
      starting_price: "2200000",
      center: { lat: 10.2899, lng: 103.984 },
    },
    category: {
      id: "lan-bien-san-ho",
      slug: "lan-bien-san-ho",
      name: "Lặn Biển San Hô",
    },
    average_rating: "5.0",
    review_count: 312,
  },
];
