# Generated by Django 5.2.7 on 2026-10-08 06:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("session_token", models.CharField(db_index=True, max_length=128, unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("locale", models.CharField(default="vi", max_length=10)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Conversation",
                "verbose_name_plural": "AI Conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AssistantKnowledgeChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("tour", "Tour du lịch"),
                            ("destination", "Điểm đến"),
                            ("place", "Danh thắng / Trải nghiệm"),
                            ("article", "Bài viết / Stories"),
                            ("policy", "Chính sách / Dịch vụ"),
                        ],
                        db_index=True,
                        default="tour",
                        max_length=32,
                    ),
                ),
                ("entity_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("entity_slug", models.CharField(db_index=True, max_length=128)),
                ("title", models.CharField(max_length=255)),
                ("content_vi", models.TextField()),
                ("content_en", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("embedding", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "verbose_name": "Knowledge Chunk",
                "verbose_name_plural": "Knowledge Chunks",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_slug"], name="assistant_a_entity__5375d9_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AssistantLeadCapture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("contact_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(db_index=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("preferred_destination", models.CharField(blank=True, max_length=255)),
                ("estimated_pax", models.PositiveIntegerField(default=1)),
                ("budget_range", models.CharField(blank=True, max_length=128)),
                ("travel_dates", models.CharField(blank=True, max_length=128)),
                ("chat_summary", models.TextField(blank=True)),
                (
                    "sync_state",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ đồng bộ"),
                            ("synced", "Đã đồng bộ CRM"),
                            ("failed", "Lỗi đồng bộ"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("odoo_lead_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="assistant.assistantconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Lead Capture",
                "verbose_name_plural": "AI Lead Captures",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssistantMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        default="user",
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("structured_payload", models.JSONField(blank=True, default=dict)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="assistant.assistantconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Message",
                "verbose_name_plural": "AI Messages",
                "ordering": ["created_at"],
            },
        ),
    ]
