# Generated by Django 5.2.7 on 2026-10-10 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '__first__'),
        ('bookings', '0002_add_payment_fields'),
        ('restaurants', '__first__'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_bookings', to='accommodations.accommodation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='item_type',
            field=models.CharField(choices=[('tour', 'Tour du lịch'), ('accommodation_referral', 'Giới thiệu khách sạn'), ('restaurant_referral', 'Giới thiệu nhà hàng')], db_index=True, default='tour', max_length=32),
        ),
        migrations.AddField(
            model_name='booking',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='booking',
            name='referral_partner_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='referral_target_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_bookings', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('paid', 'Đã thanh toán'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy'), ('completed', 'Hoàn thành'), ('referred', 'Đã chuyển đối tác')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['item_type', 'status', 'created_at'], name='idx_booking_type_stat_dt'),
        ),
    ]
