# Generated by Django 5.2.7 on 2026-10-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('vnpay', 'VNPay'), ('vietqr', 'VietQR'), ('cash', 'Tiền mặt'), ('momo', 'MoMo'), ('zalopay', 'ZaloPay'), ('stripe', 'Stripe')], db_index=True, default='vnpay', max_length=32),
        ),
    ]
