# Generated by Django 5.2.7 on 2026-10-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
