import { Customer } from "./types";

export const TEMPLATE_CUSTOMERS: Customer[] = [
  {
    id: "cust-1",
    name: "Jane Cooper",
    company: "Microsoft",
    phone: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
    tourPackage: "Vietnam Heritage Grand Tour (Hà Nội - Hạ Long - Hội An)",
    joinDate: "12/03/2026",
    totalSpent: "$2,450",
    notes: "VIP traveler, prefers 5-star ocean-view cabins on Hạ Long Bay cruise.",
  },
  {
    id: "cust-2",
    name: "Floyd Miles",
    company: "Yahoo",
    phone: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
    tourPackage: "Phú Quốc Luxury Beach Retreat",
    joinDate: "28/02/2026",
    totalSpent: "$1,890",
    notes: "Requested itinerary for scuba diving at An Thới archipelago.",
  },
  {
    id: "cust-3",
    name: "Ronald Richards",
    company: "Adobe",
    phone: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
    tourPackage: "Sa Pa Fansipan Explorer & Trekking",
    joinDate: "15/01/2026",
    totalSpent: "$1,200",
    notes: "Interested in mountain photography tours.",
  },
  {
    id: "cust-4",
    name: "Marvin McKinney",
    company: "Tesla",
    phone: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
    tourPackage: "Tràng An - Bái Đính UNESCO Eco Expedition",
    joinDate: "04/04/2026",
    totalSpent: "$980",
    notes: "Vegetarian dietary preferences confirmed.",
  },
  {
    id: "cust-5",
    name: "Jerome Bell",
    company: "Google",
    phone: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
    tourPackage: "Hội An Lantern Festival & Cooking Class",
    joinDate: "19/03/2026",
    totalSpent: "$1,650",
    notes: "Family booking with 2 children.",
  },
  {
    id: "cust-6",
    name: "Kathryn Murphy",
    company: "Microsoft",
    phone: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
    tourPackage: "Huế Imperial City Cultural Journey",
    joinDate: "22/03/2026",
    totalSpent: "$2,100",
    notes: "Special private guide for Dai Noi & Thien Mu Pagoda.",
  },
  {
    id: "cust-7",
    name: "Jacob Jones",
    company: "Yahoo",
    phone: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
    tourPackage: "Mekong Delta River Safari (Cần Thơ - Bến Tre)",
    joinDate: "08/04/2026",
    totalSpent: "$1,420",
    notes: "Floating market photography excursion.",
  },
  {
    id: "cust-8",
    name: "Kristin Watson",
    company: "Facebook",
    phone: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: "Inactive",
    tourPackage: "Đà Lạt Pine Forests & Coffee Highlands",
    joinDate: "11/02/2026",
    totalSpent: "$850",
    notes: "Requested customized itinerary for honeymoon trip.",
  },
];

export const VIETNAM_TRAVEL_CUSTOMERS: Customer[] = [
  {
    id: "vn-1",
    name: "Hoàng Anh Tuấn",
    company: "VinFast Group",
    phone: "0912 345 678",
    email: "tuan.hoang@vinfast.vn",
    country: "Việt Nam (Hà Nội)",
    status: "Active",
    tourPackage: "Du thuyền 5 sao Vịnh Hạ Long (3N2Đ)",
    joinDate: "02/05/2026",
    totalSpent: "14.500.000 ₫",
    notes: "Đoàn doanh nghiệp 12 người, yêu cầu phòng President Suite.",
  },
  {
    id: "vn-2",
    name: "Nguyễn Thị Mai Phương",
    company: "Vietcombank",
    phone: "0988 765 432",
    email: "phuong.ntm@vietcombank.com.vn",
    country: "Việt Nam (TP.HCM)",
    status: "Active",
    tourPackage: "Tràng An - Hang Múa - Tam Cốc (2N1Đ)",
    joinDate: "14/04/2026",
    totalSpent: "6.800.000 ₫",
    notes: "Đặt vé thuyền riêng và hướng dẫn viên song ngữ.",
  },
  {
    id: "vn-3",
    name: "Trần Đức Minh",
    company: "VNG Corporation",
    phone: "0903 112 233",
    email: "minh.td@vng.com.vn",
    country: "Việt Nam (Đà Nẵng)",
    status: "Active",
    tourPackage: "Phố cổ Hội An & Lặn ngắm san hô Cù Lao Chàm",
    joinDate: "20/04/2026",
    totalSpent: "8.900.000 ₫",
    notes: "Yêu cầu cano cao tốc và thiết bị lặn chuyên nghiệp.",
  },
  {
    id: "vn-4",
    name: "Lê Thu Hà",
    company: "FPT Telecom",
    phone: "0934 556 677",
    email: "ha.lt@fpt.com.vn",
    country: "Việt Nam (Huế)",
    status: "Inactive",
    tourPackage: "Di sản Cố đô Huế & Nghe ca Huế trên Sông Hương",
    joinDate: "01/03/2026",
    totalSpent: "4.200.000 ₫",
    notes: "Chờ xác nhận vé máy bay khứ hồi.",
  },
  {
    id: "vn-5",
    name: "David Wilson",
    company: "Cathay Pacific",
    phone: "+852 9123 4567",
    email: "david.w@cathaypacific.com",
    country: "Hong Kong",
    status: "Active",
    tourPackage: "Chinh phục đỉnh Fansipan Sa Pa & Bản Cát Cát",
    joinDate: "18/04/2026",
    totalSpent: "11.200.000 ₫",
    notes: "Đặt cáp treo Sun World và phòng view thung lũng Mường Hoa.",
  },
  {
    id: "vn-6",
    name: "Emma Watson",
    company: "British Council VN",
    phone: "+44 7700 900123",
    email: "emma.w@britishcouncil.org",
    country: "United Kingdom",
    status: "Active",
    tourPackage: "Đà Lạt Săn Mây & Thung Lũng Tình Yêu",
    joinDate: "25/04/2026",
    totalSpent: "7.500.000 ₫",
    notes: "Yêu cầu chụp ảnh nghệ thuật bình minh đồi chè Cầu Đất.",
  },
  {
    id: "vn-7",
    name: "Kenji Takahashi",
    company: "Toyota Vietnam",
    phone: "+81 90 1234 5678",
    email: "kenji.t@toyota.co.jp",
    country: "Japan",
    status: "Active",
    tourPackage: "Phú Quốc Sunset Town & Cáp treo Hòn Thơm",
    joinDate: "29/04/2026",
    totalSpent: "16.800.000 ₫",
    notes: "Phòng nghỉ tại JW Marriott Emerald Bay.",
  },
  {
    id: "vn-8",
    name: "Sarah Jenkins",
    company: "Traveloka Partner",
    phone: "+65 8123 4567",
    email: "sarah.j@traveloka.com",
    country: "Singapore",
    status: "Inactive",
    tourPackage: "Khám phá Chợ nổi Cái Răng & Vườn trái cây Phong Điền",
    joinDate: "10/03/2026",
    totalSpent: "5.400.000 ₫",
    notes: "Khách gia đình quan tâm trải nghiệm ẩm thực Tây Đô.",
  },
];

export const PARTNER_INQUIRIES: Customer[] = [
  {
    id: "part-1",
    name: "Du thuyền Paradise Hạ Long",
    company: "Paradise Vietnam Hospitality",
    phone: "0945 678 901",
    email: "partner@paradisevietnam.com",
    country: "Quảng Ninh",
    status: "Active",
    tourPackage: "Hợp tác phân phối độc quyền Tour Vịnh Hạ Long 5 sao",
    joinDate: "10/01/2026",
    totalSpent: "500.000.000 ₫",
    notes: "Đối tác du thuyền hạng sang hàng đầu miền Bắc.",
  },
  {
    id: "part-2",
    name: "Khách sạn Mường Thanh Luxury",
    company: "Mường Thanh Hospitality Group",
    phone: "0918 889 900",
    email: "sales.dn@muongthanh.vn",
    country: "Đà Nẵng",
    status: "Active",
    tourPackage: "Hợp đồng đối tác lưu trú toàn quốc cho khách Star Travels",
    joinDate: "15/02/2026",
    totalSpent: "320.000.000 ₫",
    notes: "Cam kết ưu đãi phòng tốt nhất cho mùa cao điểm.",
  },
  {
    id: "part-3",
    name: "Tràng An Eco-Lodge Ninh Bình",
    company: "Tràng An Heritage Tourism",
    phone: "0977 123 789",
    email: "booking@tranganecolodge.vn",
    country: "Ninh Bình",
    status: "Active",
    tourPackage: "Chuỗi tour bền vững và xe đạp khám phá danh thắng",
    joinDate: "03/03/2026",
    totalSpent: "180.000.000 ₫",
    notes: "Đối tác sinh thái đạt chứng nhận du lịch xanh.",
  },
  {
    id: "part-4",
    name: "Xe Limousine VIP Bắc Nam",
    company: "Vận tải Du lịch An Khang",
    phone: "0966 554 433",
    email: "contact@vipvan.vn",
    country: "Hà Nội",
    status: "Inactive",
    tourPackage: "Dịch vụ đưa đón sân bay Nội Bài & tour trọn gói",
    joinDate: "20/01/2026",
    totalSpent: "95.000.000 ₫",
    notes: "Đang tái thẩm định hồ sơ bảo hiểm hành khách.",
  },
];
