# Generated by Django 5.2.7 on 2026-10-10 13:57

import uuid
from decimal import Decimal

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("destinations", "0002_add_bilingual_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(max_length=128, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                ("cuisine_type", models.CharField(max_length=64)),
                ("price_range", models.CharField(max_length=16)),
                ("address", models.TextField()),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("signature_dishes", models.JSONField(default=list)),
                ("opening_hours", models.JSONField(default=dict)),
                ("image_url", models.CharField(max_length=512)),
                ("gallery", models.JSONField(default=list)),
                ("contact_type", models.CharField(max_length=16)),
                ("contact_value", models.CharField(max_length=512)),
                (
                    "partner_commission_rate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "rating_average",
                    models.DecimalField(decimal_places=2, default=Decimal("5.00"), max_digits=3),
                ),
                ("rating_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="restaurants",
                        to="destinations.destination",
                    ),
                ),
            ],
            options={
                "db_table": "restaurants_restaurant",
                "ordering": ["-rating_average", "name"],
                "indexes": [
                    models.Index(
                        fields=["destination", "is_active"], name="idx_restaurant_destination"
                    )
                ],
            },
        ),
    ]
